### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by builtinfunction** [shadow/shadow-plugin-tor#66]
When I try to run generate.py to generate my own tor network as instructed in the wiki, some warning appeared like below:
```
python ~/shadow-plugin-tor/tools/generate.py --nauths 1 --nrelays 20 --nclients 200 --nservers 20 --fweb 0.90 --fbulk 0.10 --nperf50k 10 --nperf1m 10 --nperf5m 10 ../alexa-top-1000-ips.csv ../consensuses-2018-12/01/2018-12-01-12-00-00-consensus ../server-descriptors-2018-12/ ../extra-infos-2018-12/ ../userstats-relay-country.csv
[2018-12-17 20:52:53.162190] Warning: Cant find code for IP '141.101.120.54' Num '2372237366', defaulting to 'US'
[2018-12-17 20:52:54.540262] Warning: Cant find code for IP '88.221.76.220' Num '1490898140', defaulting to 'US'
[2018-12-17 20:52:56.936998] Warning: Cant find code for IP '92.122.26.149' Num '1551506069', defaulting to 'US'
[2018-12-17 20:52:57.184406] Warning: Cant find code for IP '198.41.209.132' Num '3324629380', defaulting to 'US'
Traceback (most recent call last):
  File "/home/tomoya/shadow-plugin-tor/tools/generate.py", line 1135, in <module>
    main()
  File "/home/tomoya/shadow-plugin-tor/tools/generate.py", line 217, in main
    generate(args)
  File "/home/tomoya/shadow-plugin-tor/tools/generate.py", line 268, in generate
    clientCountryCodes = getClientCountryChoices(args.connectingusers)
  File "/home/tomoya/shadow-plugin-tor/tools/generate.py", line 704, in getClientCountryChoices
    n = int(parts[2])                    #parts[2] == num of clients
ValueError: invalid literal for int() with base 10: ''
```
I don't know how to solve this problem.

**Comment by robgjansen** [comment]
It seems that you are getting that error because the file that you are using is in a format that the script did not expect.

I pushed a new commit 67e966692f55aae739fe4cc7b30334bf133615c9 which *might* help, but might not. Please pull to the latest version.

Also, make sure you are using the latest users file from Tor:
wget https://metrics.torproject.org/userstats-relay-country.csv

Using those two together worked for me. Let me know if this fixes it.

**Comment by robgjansen** [comment]
If the above suggestion does not fix it, please add a print statement following line 693 in the generate script:
https://github.com/shadow/shadow-plugin-tor/blob/67e966692f55aae739fe4cc7b30334bf133615c9/tools/generate.py#L692-L695

Add `print line,` and then post here the last line that is printed before the error occurs.

**Comment by builtinfunction** [comment]
I fixed the problem. It seems that it's because the file I downloaded has some mistakes which result in the shortage of user numbers in the last `line`. And I re-download the file, problem fixed. The `generate ` script is totally cool actually.

**Comment by builtinfunction** [comment]
Thanks very much for your help.

**Comment by robgjansen** [comment]
Great, have fun with your simulations!
